baseURL = 'https://nicola.strappazzon.me/'
languageCode = 'es-es'
title = 'Nicola Strappazzon'
theme = 'terminal'
pagination.pagerSize = 10
copyright = '© 2025 Nicola Strappazzon'

[params]
	centerTheme = true
#	showMenuItems = 4
	Toc = true

[params.logo]
    logoText = "Nicola Strappazzon"
